print('hello there')
print("what's your name?")
name = input()
print('hello there' + ' ' + name)
print('length of your name is:')
print(len(name))
print("What's your age")
age = input()
print('You will be' + ' ' + str(int(age)+1) + ' ' + 'in a year')